import type { Metadata } from 'next';

import { Toaster } from '@/shared/components/sonner';

import '@/shared/styles/globals.css';

export const metadata: Metadata = {
  title: 'Sorou | 揃う',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="antialiased">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
